### ISSUE TITLE
DSL class `script_score` does not exist in query.

### ISSUE THREAD

**Issue by mustfkeskin** [elastic/elasticsearch-dsl-py#1478] opened 2021-01-14 14:58 UTC
Hello i want query my vector with knn
But I got error
**DSL class `script_score` does not exist in query.**

```
ms = MultiSearch(using=es, index="image-search")
for vector in vectors :
    ms = ms.add(Search().from_dict(get_body_for_image_search(categoryId, brandId, vector)))
```

```
{"size": 100,
                 "query": {
                    "script_score": {
                      "query": {
                        "bool": {
                          "must": 
                            [
                            {"term" : { "categoryId" : categoryId}},
                            {"term" : { "brandId" : brandId}}
                            ]
                        }
                      },
                      "script": {
                        "lang": "knn",
                        "source": "knn_score",
                        "params": {
                          "field": "image_vector",
                          "query_value": vector,
                          "space_type": "cosinesimil"
                        }
                      }
                    }
                  },
                    "fields": ["contentId"],
                    "_source": False
                }
```

**Comment by sethmlarson** [comment] 2021-01-14 22:07
Closing as duplicate of https://github.com/elastic/elasticsearch-dsl-py/issues/1479

**Closed by sethmlarson** 2021-01-14 22:07 UTC
