### ISSUE TITLE
Looping Search object results in 100% cpu usage?

### ISSUE THREAD

**Issue by johnraz** [elastic/elasticsearch-dsl-py#299] opened 2015-11-15 13:46 UTC
Hi,

I know it is not the expected usage but I'm wondering why doing something like this:

```
search = MyDocType.search()
[x for x in search]
```

Will make my python process go crazy and use 100% of the cpu for, like, forever (honestly I didn't wait for more than 5mn on this ;-))

Any thoughts ?

**Comment by HonzaKral** [comment] 2015-11-15 17:54
This is a duplicate of https://github.com/elastic/elasticsearch-dsl-py/issues/279

**Closed by HonzaKral** 2015-11-15 17:54 UTC
