### ISSUE TITLE
Suggest (and other) queries always include match_all search

### ISSUE THREAD

**Issue by Paulius-Maruska** [elastic/elasticsearch-dsl-py#924] opened 2018-06-25 08:20 UTC
If I have an index like this:
```python
from elasticsearch_dsl import DocType, Completion

class ProductCompletion(DocType):
    name = Completion()
```

And then I do the suggest query like this:
```python
query = ProductCompletion.search()
query = query.index('product-name-index')
query = query.suggest("name-suggest", "foo", completion={"field": "name", "size": 10})
```

Then the output of `query.to_dict()` is:
```json
{
    "query": {
        "match_all": {}
    },
    "suggest": {
        "name-suggest": {
            "text": "foo",
            "completion": {
                "field": "name",
                "size": 10
            }
        }
    }
}
```

According to elasticsearch documentation, suggest query can happen on it's own - the `query->match_all` is completely unnecessary. Also, this increases the size of the response sent back from ES.

Looking at the https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L614
It seems that "search" will always be added to the query sent to ES no matter what.

I only started learning ES recently and my understanding is rather limited. I apologize, if I misunderstood the ES docs and this "search" portion of the query is actually required.

**Comment by HonzaKral** [comment] 2018-06-25 11:32
Thank you for the report, this is a duplicate of https://github.com/elastic/elasticsearch-dsl-py/issues/903 so I would prefer to discuss there.

**Comment by HonzaKral** [comment] 2018-06-28 12:13
I am sorry, this is a slightly different issue than #903.

The problem is that we have no good way of detecting whether a user has explicitly asked for a query to be `match_all` of if that is just the default. The workaround is to supply `size: 0` (by slicing `s = s[0:0]`) which will make sure no hits are returned.

I will also leave this open to remind us that we should try and detect if a `query` is empty or `match_all` since elasticsearch has different defaults in different situations.

**Closed** 2018-06-28 15:29 UTC

**Comment by Paulius-Maruska** [comment] 2018-07-05 12:13
I have just updated to a new version in my project and it woks now as expected.

Thank you very much.
