### ISSUE TITLE
Possible memory leak running search.execute()

### ISSUE THREAD

**Issue by amaschas** [elastic/elasticsearch-dsl-py#1303] opened 2020-01-23 19:03 UTC
Elastic Search v6.8.0

Tested versions of elasticsearch-dsl
6.4.0, 7.1.0

Tested with version of elasticsearch-py
6.4.0, 7.1.0, 7.5.1

Over the last few weeks, my team observed one of our services (a API built in Flask) repeatedly eating up all available container memory and restarting. We had recently implemented an ES integration on the backend, so our investigation focussed on that integration. We created a test endpoint that allowed us to isolate the ES integration and called the endpoint repeatedly to see if we could replicate the problem. We observed the memory footprint steadily rising, and using the memory_profiler package, we were able to track the increase to the `search.execute()` statement in our ES implementation. The output from the profiler is included below.

```
rex_1  | Line #    Mem usage    Increment   Line Contents
rex_1  | ================================================
rex_1  |     17     84.6 MiB     84.6 MiB       @profile
rex_1  |     18                                 def category_level_location_match(self, level: str, category: str, latitude: float, longitude: float, return_top_n: int = 30):  # type: ignore
rex_1  |     19     84.6 MiB      0.0 MiB           search = Search(using=self.es_obj, index=config.JOBS_INDEX)
rex_1  |     20     84.6 MiB      0.0 MiB           search = search[0:return_top_n]  # retrieves results 0 to n (instead of the default first 10 results)
rex_1  |     21
rex_1  |     22                                     # Get live jobs and match level and category
rex_1  |     23     84.6 MiB      0.0 MiB           search_query = Q("bool", must=[Q("match", state="live"),
rex_1  |     24     84.6 MiB      0.0 MiB                                          Q("match", levels=level),
rex_1  |     25     84.6 MiB      0.0 MiB                                          Q("match", categories=category)])
rex_1  |     26
rex_1  |     27                                     # Distance filtering
rex_1  |     28     84.6 MiB      0.0 MiB           search_filter = search.query(search_query).filter(self.distance_filter(latitude=latitude, longitude=longitude))
rex_1  |     29
rex_1  |     30                                     # Distance sorting
rex_1  |     31     84.6 MiB      0.0 MiB           search = search_filter.sort(self.distance_sorter(latitude=latitude, longitude=longitude))
rex_1  |     32
rex_1  |     33     84.7 MiB      0.1 MiB           return search.execute()
```

We tried several strategies to get execute to release memory on each call, including using a shared search instance across each call, manually calling `del` on the search instance, and manually calling the garbage collector, but the call still exhibited the same behavior.

**Comment by HonzaKral** [comment] 2020-01-23 22:42
Thank you for noticing this, from first look it looks like the problem is with the `Response` object being cached on `Search` object while also holding a reference to the `Search` object (0, 1).

It looks like a good use of `weakref` might clear things out, also not keeping the `Search` object around after `Response` is fully processed. Right now we are processing the `hits` and `aggs` in a lazy fashion so we need to make sure to keep the `Search` object around.

I tried creating a branch using a `weakref` for the response cache in `weakref-cache-1303`, would you mind testing that out to verify the approach?

0 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/response/__init__.py#L7
1 - https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L693

**Comment by amaschas** [comment] 2020-01-23 23:04
Thanks for the quick response!

I ran my test with your branch, but unfortunately the memory issue persists. Anything else I can do to help debug?

**Comment by HonzaKral** [comment] 2020-01-23 23:20
If you could also try branch `nocache` which completely removes the caching of `_response` on the search object. I tried running it 1000 in a loop with a memory profiler and saw significantly less memory usage. There is always going to be some increase of memory usage with `execute` as the data coming from ES need to be stored in memory but it should not keep growing. When I now keep running this code I no longer see any memory increments after the first few iterations...

**Comment by HonzaKral** [comment] 2020-01-23 23:32
btw how are you testing this? I am getting different results, with a test file of:
```python
from elasticsearch_dsl import connections, Search

from memory_profiler import profile

connections.create_connection()

@profile
def my_func():
    for x in range(1000):
        s = Search()
        s = s[:100]
        r = s.execute()
    return r

my_func()
my_func()
my_func()
```

i am getting:
```
Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     25.7 MiB     25.7 MiB   @profile
     8                             def my_func():
     9     29.6 MiB      0.0 MiB       for x in range(1000):
    10     29.6 MiB      0.0 MiB           s = Search()
    11     29.6 MiB      0.0 MiB           s = s[:100]
    12     29.6 MiB      1.5 MiB           r = s.execute()
    13     28.1 MiB      0.0 MiB       return r


Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     28.1 MiB     28.1 MiB   @profile
     8                             def my_func():
     9     29.6 MiB      0.0 MiB       for x in range(1000):
    10     29.6 MiB      0.0 MiB           s = Search()
    11     29.6 MiB      0.0 MiB           s = s[:100]
    12     29.6 MiB      1.5 MiB           r = s.execute()
    13     29.6 MiB      0.0 MiB       return r


Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     29.6 MiB     29.6 MiB   @profile
     8                             def my_func():
     9     29.6 MiB      0.0 MiB       for x in range(1000):
    10     29.6 MiB      0.0 MiB           s = Search()
    11     29.6 MiB      0.0 MiB           s = s[:100]
    12     29.6 MiB      0.0 MiB           r = s.execute()
    13     29.6 MiB      0.0 MiB       return r
```

You can see that after a few iterations the memory stops growing. this is with the `weakref-cache-1303` branch, I see the same behavior with `master` branch where after a few iterations the memory stops growing and remains stable:

```
Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     25.7 MiB     25.7 MiB   @profile
     8                             def my_func():
     9     58.2 MiB      0.0 MiB       for x in range(1000):
    10     58.2 MiB      0.0 MiB           s = Search()
    11     58.2 MiB      0.0 MiB           s = s[:100]
    12     58.2 MiB      2.0 MiB           r = s.execute()
    13     57.4 MiB      0.0 MiB       return r


Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     57.4 MiB     57.4 MiB   @profile
     8                             def my_func():
     9     59.3 MiB      0.0 MiB       for x in range(1000):
    10     59.3 MiB      0.0 MiB           s = Search()
    11     59.3 MiB      0.0 MiB           s = s[:100]
    12     59.3 MiB      1.1 MiB           r = s.execute()
    13     58.5 MiB      0.0 MiB       return r


Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     58.5 MiB     58.5 MiB   @profile
     8                             def my_func():
     9     59.3 MiB      0.0 MiB       for x in range(1000):
    10     59.3 MiB      0.0 MiB           s = Search()
    11     59.3 MiB      0.0 MiB           s = s[:100]
    12     59.3 MiB      0.6 MiB           r = s.execute()
    13     59.3 MiB      0.0 MiB       return r


Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     59.3 MiB     59.3 MiB   @profile
     8                             def my_func():
     9     59.5 MiB      0.0 MiB       for x in range(1000):
    10     59.5 MiB      0.0 MiB           s = Search()
    11     59.5 MiB      0.0 MiB           s = s[:100]
    12     59.5 MiB      0.1 MiB           r = s.execute()
    13     57.8 MiB      0.0 MiB       return r


Filename: prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     7     57.8 MiB     57.8 MiB   @profile
     8                             def my_func():
     9     58.5 MiB      0.0 MiB       for x in range(1000):
    10     58.5 MiB      0.0 MiB           s = Search()
    11     58.5 MiB      0.0 MiB           s = s[:100]
    12     58.5 MiB      0.5 MiB           r = s.execute()
    13     55.9 MiB      0.0 MiB       return r
```

**Comment by amaschas** [comment] 2020-01-24 17:17
OK, I'm seeing what you're seeing now, I just had to run it for longer to hit equilibrium. I was running 1000 requests serially, at which point memory was still going up, but I added 3 concurrent 1000 request loops and managed to get memory usage to plateau.

**Comment by HonzaKral** [comment] 2020-01-24 21:08
Thank you for confirming. Closing the issue then, please feel free to reopen if you discover any other issue, I appreciate you checking into it!

**Closed by HonzaKral** 2020-01-24 21:08 UTC

**Comment by amaschas** [comment] 2020-01-24 22:00
Excellent, thanks! Will this eventually get merged into the next release?

**Comment by HonzaKral** [comment] 2020-01-24 22:46
I am hesitant to merge it as it is not strictly required and makes the caching less efficient by a lot - even without the patch, on `master` we see the same behavior of the memory only growing up to a point and then stopping without sacrificing any of the caching.

**Comment by amaschas** [comment] 2020-01-27 18:02
Hrm, sorry but I'm a little confused. I'm seeing this issue in a release version of this library. In production it's so bad that the instance we're running eats all of the memory and crashes multiple times a day.

**Comment by HonzaKral** [comment] 2020-01-27 18:23
I understand, but I cannot replicate it - see the example run above where even the version in the `master` branch stops growing after a while. It has larger memory footprint for sure, but doesn't grow indefinitely as a code with memory leak would...

Could you perhaps share some code that replicates the issue you are seeing if executed many times and given enough memory?

We can certainly do many things to (optionally) reduce memory footprint, I pushed new code to the `nocache` branch that is more in sync with the codebase (also tests pass) that would allow you to completely bypass the issue by passing `ignore_cache=True` to `execute()`, would that improve the situation enough?

**Comment by amaschas** [comment] 2020-01-27 18:50
Ah, ok, I'm sorry I thought you were able to replicate it on your end. I'll see if I can construct a test case to determine whether it's specific to our dataset and implementation. I'll also give the nocache branch a try and see if I can get our memory usage to plateau by adding more memory to the instance. Thanks for clarifying!
