### ISSUE TITLE
TransportError when querying unicode

### ISSUE THREAD

**Issue by mochawich** [elastic/elasticsearch-dsl-py#348] opened 2016-02-28 03:26 UTC
I'm trying to execute this search

```python
index_queryset.query('multi_match', query=search, fields=['title', 'text', 'tags'], fuzziness='AUTO').execute()
```
`search` is a URL query parameter. When it is something like `Nissan maxima 2005 for sale to highest bid` everything works fine, however when it is `مكسيماللبيع لأعلى سعر 2005  لون فضي للبيع` things get funny as python converts the string to unicode. Printing the query body to console I get this on first case [only Latin letters]

> {'sort': [u'_score', {u'date_published': {'order': 'desc'}}], 'query': {'multi_match': {'fields': [u'title', u'text', u'tags'], 'fuzziness': u'AUTO', 'query': u'Nissan maxima 2005 for sale to highest bid'}}}

While on the second case [unicode] I get

> {'sort': [u'_score', {u'date_published': {'order': 'desc'}}], 'query': {'multi_match': {'fields': [u'title', u'text', u'tags'], 'fuzziness': u'AUTO', 'query': u'\u0645\u0643\u0633\u064a\u0645\u0627\u0644\u0644\u0628\u064a\u0639 \u0644\u0623\u0639\u0644\u0649 \u0633\u0639\u0631 2005  \u0644\u0648\u0646 \u0641\u0636\u064a \u0644\u0644\u0628\u064a\u0639'}}}

For that I get this error

> TransportError: TransportError(500, u'search_phase_execution_exception', u'Determinizing automaton would result in more than 10000 states.')

Now what is funny/annoying I tried to hard code the search and it worked!
```python
index_queryset.query('multi_match', query=u"مكسيماللبيع لأعلى سعر 2005  لون فضي للبيع", fields=['title', 'text', 'tags'], fuzziness='AUTO').execute()
```

Am I doing something wrong? why does it matter to ES how strings are encoded

**Comment by alejoar** [comment] 2016-02-29 14:11
@mochawich:

I never worked with Arabic characters so not sure if this would work, but you could try:
`مكسيماللبيع لأعلى سعر 2005 لون فضي للبيع.decode('utf-8')`

**Comment by HonzaKral** [comment] 2016-02-29 21:09
@mochawich thanks for such detailed version. Could I ask you what version of `elasticsearch-py` are you using? Seems like you are using a version that doesn't include https://github.com/elastic/elasticsearch-py/commit/c305dc5587963bc9e41ae8cf35bb6eff5afb199e

If possible, could you try upgrading to that version and seeing if it fixes that issue?

Thanks!

**Comment by mochawich** [comment] 2016-03-05 16:08
@alejoar unfortunately it didn't. I got exception decoding the string.

@HonzaKral I have the latest 2.3.0 `elasticsearch-py` installed.

**Comment by HonzaKral** [comment] 2016-04-09 16:04
Sorry about the delay, I tried to investigate this further, but it looks like it's an issue with elasticsearch itself - both options of json encoding are valid, the problem is with the `fuzziness=AUTO` option that you have - the arabic letters are much too complex for the calculation and an intermediary state of it would have more that 100000 states, which is not allowed in lucene/elasticsearch.

This might be solveable by using some unicode-aware analyzer (I'd have a look at the ICU plugin) or just hardcoding a level of fuzziness that works for your use case.

Either way this is inside of elasticeasr and not in the python client itself so I am closing this issue.

**Closed by HonzaKral** 2016-04-09 16:04 UTC
