### ISSUE TITLE
Conditional filtering for key values on ObjectBase

### ISSUE THREAD

**Issue by SiqiTian-minted** [elastic/elasticsearch-dsl-py#591] opened 2017-02-15 22:28 UTC
I have tracked down an issue of `ObjectBase.to_dict()` results that keys with empty values (e.g. `[]`) are missing. Apparently that's what the code does, see `elasticsearch_dsl/utils.py` line 365.

```python
    def to_dict(self):
        out = {}
        for k, v in iteritems(self._d_):
            try:
                f = self._doc_type.mapping[k]
                if f._coerce:
                    v = f.serialize(v)
            except KeyError:
                pass

            # don't serialize empty values
            # careful not to include numeric zeros
            if v in ([], {}, None):
                continue

            out[k] = v
        return out
```

This is a strong assumption on how a user what's his/her data. Could you disable this? Or make it conditional with an optional flag maybe?

**Comment by SiqiTian-minted** [comment] 2017-02-15 22:31
Also this is evil:

```
try:
    ...
except KeyError:
    pass
```

Silent fails

**Comment by HonzaKral** [comment] 2017-02-16 06:22
This is a duplicate of #460, please continue discussion there if you have any new information.

> Also this is evil:

why is it evil? The type coercion is conditional based on the field being defined or not. The field not being present (thus raising a `KeyError`) is a perfectly valid outcome that doesn't call for any outcome. To make it even more clear I updated the code in 3360ef7335d345c039575189d50b8f4b9f791c00

**Closed by HonzaKral** 2017-02-16 06:22 UTC
