### ISSUE TITLE
list(Doc.search()) provocate infinite iteration and memory consumption

### ISSUE THREAD

**Issue by alexgarel** [elastic/elasticsearch-dsl-py#306] opened 2015-12-01 17:25 UTC
version: 0.0.9
using: python3.4

It seems ``list()`` calls ``Search. __getitem__`` and not ``__iter__``
As Search.`` __getitem__`` just lazily initialize the result it feels memory with clones.

Proposed modification : make ``__getitem__`` checks ``n`` against ``self.count()`` and eventually raise ``IndexError``.

Here is a small example.

```python
    from elasticsearch_dsl.connections import connections
    from elasticsearch_dsl import Index, DocType, String


    class SimpleDoc(DocType):
        text = String(index = 'not_analyzed')

        class Meta:
            index = "test"

    connections.create_connection()
    index = Index("test")
    index.doc_type(SimpleDoc)
    if index.connection.indices.exists(index._name):
        index.delete()
    index.create()


    SimpleDoc.init()

    d = SimpleDoc(text="testme")
    d.meta.id = 1
    d.save()

    # infinite loop
    # list(SimpleDoc.search())
    assert len(list(zip(SimpleDoc.search(), range(100)))) == 100

    # using execute is ok
    while not SimpleDoc.search().count():
        pass  # got to wait document to be ready

    assert len(list(SimpleDoc.search().execute())) == 1
```

**Comment by HonzaKral** [comment] 2015-12-01 17:28
This is a duplicate of #279 it has been fixed in master by `__iter__` calling `execute()`

Thanks for the report!

**Closed by HonzaKral** 2015-12-01 17:28 UTC

**Comment by alexgarel** [comment] 2015-12-01 17:29
Oh sorry, forgot to check closed tickets !
