### ISSUE TITLE
Paginate with scroll api in django

### ISSUE THREAD

**Issue by fatal10110** [elastic/elasticsearch-dsl-py#429] opened 2016-07-17 07:14 UTC
Hi, I have a large number of records (more than 10000) in my index, but i need only 12 of them each time (12 on page).
Is it possible to do it with scan (scroll API) and django paginator ? 

Thanks

Now i'm getting this error with standard `from - size` query:

```
TransportError(500, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [21435]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.')
```

**Comment by HonzaKral** [comment] 2016-07-18 12:37
Hi @fatal10110,

It is possible, but you'd have to implement the scanning yourself by persisting the `_scroll_id` in a session or something and requesting the next page inside the next request. This would, however, not solve a use case where user can go directly to page `1000` (as opposed to clicking `next` 1000 times).

That said it is a very expensive operation and shouldn't really be used for pagination. Deep pagination like this is super expensive when using sorting and should be avoided if at all possible. One trick to do that is to use a range filter on some (preferably unique) field the user is sorting on instead of `from`/`size` - that way you will avoid sorting tens of thousands (requiring elasticsearch to allocate memory for those) of items to just get 12 back.

Hope this helps

**Comment by HonzaKral** [comment] 2016-08-31 00:11
Closing this ticket since there is no new information. Please feel to reopen if the issue is not resolved.

**Closed by HonzaKral** 2016-08-31 00:11 UTC
