### ISSUE TITLE
Empty objects are not stored

### ISSUE THREAD

**Issue by 0x64746b** [elastic/elasticsearch-dsl-py#471] opened 2016-10-10 16:03 UTC
While it's possible to store empty objects through the API (cf https://github.com/elastic/elasticsearch/issues/4047) and the [low level client](https://github.com/elastic/elasticsearch-py), it's not possible through the `DocType` wrapper.

In addition, empty objects (e.g. stored through the low level client) are removed when updating the doc through its DSL wrapper.

If it's not possible to initialize objects, scripts have to check for the existence of such an object before each access, since it might be still `null`.

**Comment by HonzaKral** [comment] 2016-10-10 16:29
This is a duplicate of #460, let us discuss all the issues around not storing empty fields there. Thank you!

**Closed by HonzaKral** 2016-10-10 16:29 UTC

**Comment by 0x64746b** [comment] 2016-10-10 17:34
Sure, just didn't wanna hijack that issue, since it's related to retrieval/serialization, not storing.
