### ISSUE TITLE
Installation instructions are off

### ISSUE THREAD

**Issue by martinth** [elastic/elasticsearch-dsl-py#341] opened 2016-02-18 11:01 UTC
The README say:
> The recommended way to set your requirements in your setup.py or requirements.txt is:
>
> elasticsearch-dsl>=2.0.0,<3.0.0

However, this won't work since [there is no published version that is greater that 0.0.11 an pypi](https://pypi.python.org/pypi/elasticsearch-dsl). Is this intentional (i.e. you plan to bump the version in the short term) or just a mistake?

**Comment by HonzaKral** [comment] 2016-02-18 18:47
This is a duplicate of #329 Release is coming soon, we have just fallen behind

**Closed by HonzaKral** 2016-02-18 18:47 UTC
