### ISSUE TITLE
TypeError unhashable type: 'list'

### ISSUE THREAD

**Issue by Alkalit** [elastic/elasticsearch-dsl-py#599] opened 2017-02-22 09:06 UTC
```
    client = Search(using=haystack_connections['default'].get_backend().conn, index='haystack', doc_type='modelresult')
    query = \
        {
            "size": 0,

            "query" : {
                "constant_score": {
                    "filter": [
                        {
                          "missing": {
                            "field": "deleted_at"
                          }
                        }
                    ]

                }
            },

            "aggs" : {
                "occurrences_of_query" : {
                    "filter" : {
                      "match": {
                        "text": "query"
                      }
                    },

                    "aggs": {

                       "city_slug": {
                           "terms": {
                               "field": "geo_type_slug",
                               "size": 6,
                               "order": {
                                "city_distance" : "asc"
                              }
                           },
                           "aggs": {
                               "city_distance": {
                                   "avg": {
                                       "script": {
                                           "inline": "doc['coordinates'].arcDistanceInKm(ref_lat, ref_lon)",
                                           "params": {
                                                "ref_lat": 61.25595,
                                                "ref_lon": 73.384547
                                           }
                                       }
                                   }
                               }
                            }
                       }
                    }
                }
            }
        }


    searcher = client.update_from_dict(query)
    response = searcher.execute()
```
Which rises:

```
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/seo_queries/jinja/globals.py" in get_seo_queries
  174.     searcher = client.update_from_dict(query)
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/elasticsearch_dsl2/search.py" in update_from_dict
  329.             self.query._proxied = Q(d.pop('query'))
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/elasticsearch_dsl2/query.py" in Q
  27.         return Query.get_dsl_class(name)(**params)
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/elasticsearch_dsl2/utils.py" in __init__
  221.             self._setattr(pname, pvalue)
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/elasticsearch_dsl2/utils.py" in _setattr
  268.                     value = shortcut(value)
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/elasticsearch_dsl2/query.py" in Q
  40.     return Query.get_dsl_class(name_or_query)(**params)
File "/Users/alkalit/.virtualenvs/promvtor/promvtor/apps/elasticsearch_dsl2/utils.py" in get_dsl_class
  212.             return cls._classes[name]
```

Where is:
```
name 	

[{u'missing': {u'field': u'deleted_at'}}]

cls 	

<class 'elasticsearch_dsl2.query.Query'>
```

```
In [1]: import elasticsearch_dsl2

In [2]: elasticsearch_dsl2.VERSION
Out[2]: (2, 2, 0)

In [3]: import elasticsearch

In [4]: elasticsearch.VERSION
Out[4]: (2, 1, 0)
```

**Comment by HonzaKral** [comment] 2017-02-22 09:22
Hi, the problem is that `constant_score` query doesn't accept a list of queries, just a single query or filter (0). To fix this just pass it a single query instead of a list:
```
"query" : {
                "constant_score": {
                    "filter": {
                          "missing": {
                            "field": "deleted_at"
                          }
                      }
                }
            },
```

Hope this helps

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-constant-score-query.html

**Comment by Alkalit** [comment] 2017-02-22 09:45
Thx for quick response.
> the problem is that constant_score query doesn't accept a list of queries
But you are wrong. It accepts - I tested this query in my kibana with a list and it works fine. This is why I decided to use it.

And this query also works with bare ES client:

```
    client = haystack_connections['default'].get_backend().conn
    query = \
        {
            "size": 0,

            "query" : {
                "constant_score": {
                    "filter": [
                        {
                          "missing": {
                            "field": "deleted_at"
                          }
                        }
                    ]

                }
            },

            "aggs" : {
                "occurrences_of_query" : {
                    "filter" : {
                      "match": {
                        "text": "query"
                      }
                    },

                    "aggs": {

                       "city_slug": {
                           "terms": {
                               "field": "geo_type_slug",
                               "size": 6,
                               "order": {
                                "city_distance" : "asc"
                              }
                           },
                           "aggs": {
                               "city_distance": {
                                   "avg": {
                                       "script": {
                                           "inline": "doc['coordinates'].arcDistanceInKm(ref_lat, ref_lon)",
                                           "params": {
                                                "ref_lat": 61.25595,
                                                "ref_lon": 73.384547
                                           }
                                       }
                                   }
                               }
                            }
                       }
                    }
                }
            }
        }

    response = client.search(body=es_query) # works
```

The reason why I need to use a list is because actual query is a bit complicated:

```
                "constant_score": {
                    "filter": [
                        {
                          "missing": {
                            "field": "deleted_at"
                          }
                        },
                        {
                          "range": {
                            "created_at": {
                              "lt": "now"
                            }
                          }
                        },
                        {
                          "term": {
                            "ad_type": 'sell'
                          }
                        },
                        {
                          "term": {
                            "published": True
                          }
                        },
                        {
                          "term": {
                            "django_ct": "ads.ad"
                          }
                        }
                    ]
                }
```

**Comment by HonzaKral** [comment] 2017-02-22 09:49
Thanks for the additional information, I will have a look.

In the mean time the workaround is to use `{"bool": {"filter": [Q1, Q2, Q3]}}` instead of the constant query which is recommended anyway.

**Comment by mattjmcnaughton** [comment] 2017-02-25 16:39
Could this be fixed by switching the definition of `ConstantScore` from 

```
class ConstantScore(Query):
    name = 'constant_score'
    _param_defs = {'query': {'type': 'query'}, 'filter': {'type': 'query'}}
```

 to 

```
class ConstantScore(Query):
    name = 'constant_score'
    _param_defs = {'query': {'type': 'query', multi: True}, 'filter': {'type': 'query', multi: True}}
```

I submitted a pr, in case this approach would work. If not, feel free to close it (I wasn't sure about whether having `multi: True` on a `query` violated only having `multi: True` for `queries`.)

**Closed** 2017-03-20 11:17 UTC

**Comment by tylerjharden** [comment] 2017-03-27 19:48
Just a note, this is not supported functionality as far as we can test, this broke previously working functionality. I cannot find documentation on when, if at all, ElasticSearch started supporting arrays of queries underneath a constant_score query, but in version 5.0.0 it certainly does not.

Should be a regression test around this, IMO.
