### ISSUE TITLE
How to get proper date format using save() ? 

### ISSUE THREAD

**Issue by RaphaelGillet** [elastic/elasticsearch-dsl-py#1142] opened 2019-03-21 21:51 UTC
To insert data I started using `bulk` operation as I had a lot of documents. In another index (queriestest) I have a few object, and I add them one by one so I changed to use the `.save()` method but it doesn't work as expected for Date

With the bulk operation, I used only `dd/MM/yyyy HH:mm:ss` and it worked. But then when use `.save()` it changed and I had an error of format and I add `date_hour_minute_second` as the error told me it failed to parse a date like `yyyy-MM-dd'T'HH:mm:ss` but then in the ES base the format is now `yyyy-MM-dd'T'HH:mm:ss` and I want the first one `dd/MM/yyyy HH:mm:ss` 

How can I achieve that ? 

```
from datetime import datetime
from collections import deque
from elasticsearch.helpers import parallel_bulk
from elasticsearch_dsl import connections, Document, Keyword, Date

connections.create_connection(hosts=['localhost'])
indexname = "queriestest"

class Query(Document):
    class Index:
        name = ""
    class Meta:
        doc_type = "doc"

    name = Keyword()
    insertion = Date(format="dd/MM/yyyy HH:mm:ss || date_hour_minute_second")

    def set_insertion_now(self):
        self.insertion = datetime.now().strftime("%d/%m/%Y %H:%M:%S")

#########################################################
def set_data():
    for elt in ["val1", "val2"]:
        query_entry = Query(name=elt)
        query_entry.set_insertion_now()
        query_entry.save(index=indexname)

def get_data():
    for elt in ["val1", "val2"]:
        entry = Query(name=elt)
        entry.set_insertion_now()

        dico = entry.to_dict(True)
        dico['_index'] = indexname
        dico['_update'] = "create"
        yield dico
#########################################################
if __name__ == '__main__':
    Query.init(index=indexname)

    # SAVE WAY
    set_data()

    # BULK WAY
    pb = parallel_bulk(connections.get_connection(), get_data())
    deque(pb, maxlen=0)

    for hit in Query.search(index=indexname):
        print(hit.insertion)

    # 21/03/2019 16:24:15 x2 (bulk way)
    # 2019-03-21T16:24:15 x2 (save way)

```

**Comment by HonzaKral** [comment] 2019-03-21 21:53
You can supply multiple formats to elasticsearch and have it work with both, you can also implement custom serialization of your dates if you really want that format.

Closing this issue as duplicate of #1140

**Closed by HonzaKral** 2019-03-21 21:53 UTC

**Comment by RaphaelGillet** [comment] 2019-03-21 22:04
And why is the first format not used for ES ? I though every format is used for parsing, but then why the value sent to ES is different if I use bulk of save ?

**Comment by HonzaKral** [comment] 2019-03-21 22:10
Because `save` is also calling validation which parses the string into a `datetime` object while `to_dict` does no such thing. for it to be consistent you should just use `datetime` objects instead of using a string to represent a datetime value on your document object.

hope this helps!
