### ISSUE TITLE
How to change the Root Object proprieties ?

### ISSUE THREAD

**Issue by k4nar** [elastic/elasticsearch-dsl-py#220] opened 2015-07-24 15:10 UTC
Hi,
I would like to use [`dynamic_templates`](https://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-root-object-type.html#_dynamic_templates) on a `DocType`, but I don't understand where I should set it. Should it be in the `Meta` ?

**Comment by HonzaKral** [comment] 2015-07-26 14:24
This is a duplicate of https://github.com/elastic/elasticsearch-dsl-py/issues/208

thanks for the report.

**Closed by HonzaKral** 2015-07-26 14:24 UTC
