### ISSUE TITLE
GeoPoint in InnerDoc is saved as type number

### ISSUE THREAD

**Issue by Wehrlem** [elastic/elasticsearch-dsl-py#1139] opened 2019-03-18 14:17 UTC
Hi,
i have following design:
```
class Apartment(InnerDoc):
    rooms = Integer()
    floor = Keyword()
    state = Keyword()
    location = GeoPoint()
```
If i save this with for instance
` location = {'lat': 47.1999058, 'lon': -67.7838558}`
2 Fields are generated: location.lat and location.lon with the type number.

When i do the same with a Document, everything works as expected.

I'm using elasticsearch-dsl==6.3.1 and elasticsearch==6.6.2.
Am i missing something? Our is this the expected behaviour?

Thanks

**Comment by HonzaKral** [comment] 2019-03-18 17:08
Did you create the mapping first in elasticsearch by assigning this inner doc to a `Document` class and then calling `init()` on the `Document`?

It sounds like you haven't specified the mappings.

**Comment by AXGKl** [comment] 2019-03-19 14:25
Hi, have the same problem, don't know if the reason is the original.

MY root cause was that I wanted to create mapping dynamically, from a dict.

```python
import elasticsearch_dsl as ES
class MyDoc(ES.Document):
       class Index:
               name = 'mydoc-%s' % today()

# THEN the adding of attributes from a kv dict:
[setattr(MyDoc, key, es_type(value))  for key, value in mymodel.items()]

# THEN the init:
MyDoc.init()

# then the actual data
```

But hat approach totally fails. Digging into the `.init` already showed it: The actual document class is not even used for .init, the only thing passed to create the mapping is cls._index - which I did not populate.
Then it was clear: ES.Document has a metaclass, which at time of class creation already stores its attributes into something later used at .init.
Which prevents dynamic attributions between class definition and `.init`.

In my case resulting in exactly the problem of the OP.

The solution in my case was to give up dynamic definitions from a project specific config file for now, i.e. set 
```
class MyDoc(ES.Document):
       location = GeoPoint()
       (...)
```

Did not dig much further than trying multinheritance  which did not work - but I guess you could hammer in dynamically those attributes still, before .init, so they are in the mapping.
I for myself go to the low level API anyway when I have some time, it offers better batch mechanics plus streaming.

**Comment by HonzaKral** [comment] 2019-03-20 20:18
@AXGKl if you want to create the mapping dynamically you have several options. You can always use the `Mapping` class instead which is more low-level and can be constructed dynamically as you describe. You can then attach the instance to the `Document` class in the `class Meta`:

```python
m = Mapping('_doc')
for key, value in mymodel.items():
    m.field(key, value)

class MyDoc(Document):
    class Meta:
        mapping = m
```

You can also access the `Mapping` instance via `MyDoc._doc_type.mapping` which you can always add fields to later, before calling the `init()`.

You can also always pull the mappings from elasticsearch after they were created by calling `load_mappings` on the `Index` object.

**Comment by HonzaKral** [comment] 2019-03-27 23:13
Closing this as it is not reproducible, please feel free to reopen with additional information!

**Closed by HonzaKral** 2019-03-27 23:13 UTC
