### ISSUE TITLE
V-7.4.0 - The client noticed that the server is not a supported distribution of Elasticsearch

### ISSUE THREAD

**Issue by vaibhav2408** [elastic/elasticsearch-dsl-py#1522] opened 2021-08-05 07:27 UTC
**Server-side ES version** : 7.10

**Client-side elasticsearch_dsl version**: 7.4.0
**Client-side elasticsearch version**: 7.14.0

**Stack trace-** 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 281, in ping
    return self.transport.perform_request(
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 413, in perform_request
    _ProductChecker.raise_error(self._verified_elasticsearch)
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 630, in raise_error
    raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch

**Client side debug logs:**
>>> $: import elasticsearch_dsl

>>> $: `elasticsearch_dsl.__version__`
  Output - (7, 4, 0)

>>> $: from elasticsearch_dsl.connections import connections

>>> $: es_conn = connections.create_connection(hosts='host_endpoint', timeout=20)

>>> $: es_conn.ping()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 281, in ping
    return self.transport.perform_request(
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 413, in perform_request
    _ProductChecker.raise_error(self._verified_elasticsearch)
  File "/opt/ccs/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 630, in raise_error
    raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch

**Note:**
Not facing this issue with the following configuration:
`Server-side ES version`: 7.10
`Client-side elasticsearch_dsl version`: 7.3.0
`Client-side elasticsearch version`: 7.13.4

**Comment by lnielsen** [comment] 2021-08-05 08:21
Unfortunately, we're all out of luck. See https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286 and https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

**Comment by vaibhav2408** [comment] 2021-08-05 08:27
> Unfortunately, we're all out of luck. See [elastic/elasticsearch-py#1639 (comment)](https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286) and https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

Yes, downgraded the version to 7.3.0 for now.

**Comment by sethmlarson** [comment] 2021-08-05 11:36
Closing this as duplicate of https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286

**Closed by sethmlarson** 2021-08-05 11:36 UTC
