### ISSUE TITLE
Serious performance degradation with deserializing response

### ISSUE THREAD

**Issue by alvinchow86** [elastic/elasticsearch-dsl-py#210] opened 2015-07-22 00:49 UTC
Sorry this is not going to be a great bug report right now, but I suspect there might be a performance issue with generating DocType instances after doing a search (`search.execute()`). I will work on generating some sort of test case but figured I'd report this now.

I noticed this for an operation where I needed around 200 objects, and I noticed that it took an unexpectedly long time. After doing some line profiling, I found that the actual Elasticsearch query took very little time, but there was about 1-2 seconds spent generating the `DocType` objects (which happens when you start to access/iterate through the results). This slowdown was present even as I removed fields from the mapping, although more fields (including nested ones) does correlate with more CPU time. I got as far as noticing that a lot of time is in `to_python()`

For now my short-term fix is to avoid running `.execute()` and just using the lower-level elasticsearch-python client. Even if I do something like recursively transform the response into a `AttrDict` like object, it is still orders of magnitude faster.

I'm guessing in the majority of applications (search) where only 10-20 are loaded at a time, this issue was sort of masked.

This is on Python 2.7

**Comment by HonzaKral** [comment] 2015-07-26 14:19
Thanks for the report. I assume the problem is that we try to convert all the fields into their proper python types upon initialization.

I see several solutions for this - makes things lazy, build a list of fields where translation is required from ES (`Date` and `Object`/`Nested` essentially) and only translate those. The second solution seems much easier to implement so I will start with that, after adding some benchmark code.

**Comment by HonzaKral** [comment] 2015-07-27 14:02
I added some improvements in e06f4553888090ce1f9ce39a56a62d01fc0bf3e4 and 1d482b5c08749ff57a785faca5ff63d4d4a3b93b. Could you please verify that you see some speedup?

I am not sure what we can do next - we can make things lazier by coercing things only on read time but that might make things even slower (if all expenses were added together) and the code would be much more complex.

**Comment by alvinchow86** [comment] 2015-07-27 23:39
Thanks for the improvements! I do see some nontrivial speed up (about 40%) or from average of to about 320ms to 230ms for the part of my code that deserializes the results. In my use case though it's still a bit slow to completely switch back to using DSL.

I'll do some profiling on my own to see if there's something else going on

For some reference, I do have some nested fields (one of which is an array of about a dozen objects, which has a handful of string, integer, datetime) fields

**Comment by HonzaKral** [comment] 2015-07-27 23:42
I would guess that a lot of the time is being spent on the datetimes, would you mind trying a quick check for me? Change the `Date` field to `String` (no need to reindex or change anything else, it won't alse break anything) and run the query, do you see any improvement there?

**Comment by alvinchow86** [comment] 2015-07-27 23:59
Thanks for the suggestion - I actually did try this (changing to String, and even just removing the field in the `DocType`) and there was just a minimal improvement. Removing this entire Nested field led to a substantial improvement though

The nested field looks something like
```python
    items = Nested(
        properties={
            'type': String(index='not_analyzed'),
            'num1': Integer(),
            'num2': Integer(),
            'num3': Integer(),
            'some_datetime': String(),
        }
    )
```

For some context, what I'm doing now is transforming the result recursively into a nested Bunch structure (https://pypi.python.org/pypi/bunch/1.0.1), which is much faster. It doesn't do Python type conversions though, but I could try adding that for some things like datetimes and see if it leads to the same slowdown as with DSL

**Comment by HonzaKral** [comment] 2015-07-28 00:06
Thanks for trying it out!

Yeah, using the `Nested` field triggers the same mechanism for every nested document since it needs to wrap the nested documents in the appropriate class and deserialize any potential fields on it (like the date).

I will try to investigate more but unfortunately I don't think there is much more we can do here - this is the price of the convenience of `DocType`. Tanstaafl.

**Comment by HonzaKral** [comment] 2015-07-28 00:08
btw what advantage does Bunch give you over the raw `AttrDict`s?

**Comment by alvinchow86** [comment] 2015-07-28 00:16
nothing, I just wanted to try something completely different - at the time I suspected some performance issue with AttrDict and was trying to test this hypothesis

**Comment by HonzaKral** [comment] 2015-08-27 21:19
There is no other obvious thing we can do here so I will close this for now.

Thanks for raising the issue, hopefully it helped.

**Closed by HonzaKral** 2015-08-27 21:19 UTC

**Comment by wanthalf** [comment] 2023-11-23 12:41
I have a similar problem. Deserialization uses a lot of time. I am sending a cProfiler output in attachment. The document structure contains3 levels of nested documents. Each nested item has one datetime attribute.
(Now using latest version 8.)

[cunit.prof.txt](https://github.com/elastic/elasticsearch-dsl-py/files/13449879/cunit.prof.txt)

**Comment by wanthalf** [comment] 2023-12-13 12:11
So, it seems the performance penalty depends heavily on nested objects and their amount. I use three levels and the amount varies. The speed seems to decrease especially when there are more objects on the second and third level (despite the fact it is just about a dozen objects).

The performance seems also significantly worse in version 8 than in version 7. But I cannot guess how much of it is possibly caused by added complexity in the newer version of my application. Anyway, getting rid of the elasticsearch-dsl deserialization into Document objects and using pure elasticsearch-py, the speedup seems about an order of magnitude (if not more) and it becomes still several times faster than using the older version of my application based on version 7.

**Comment by pquentin** [comment] 2023-12-13 12:13
Hello @wanthalf! Would you mind opening a new issue with your findings, and attach a flame graph from py-spy instead? https://github.com/benfred/py-spy cProfiler is a deterministic profiler which can introduce large biases.

**Comment by wanthalf** [comment] 2023-12-13 12:21
Thanks for advice! I will try to find some time and if I get some relevant results, I will create a new issue. Now I am just happy that I managed to speedup my searches significantly by avoiding the elasticsearch-dsl, but I still use the Document object models to deal with individual documents and their (manual) editing.
