### ISSUE TITLE
Document mapping type name can't start with '_' while deleting document

### ISSUE THREAD

**Issue by akashtalole** [elastic/elasticsearch-dsl-py#820] opened 2018-01-24 04:38 UTC
client = Elasticsearch(hosts= '[172.16.2.121]')
s = Search(using=client, index="mqtt-index-2018.01.24").query("match", value=10)
response = s.delete()

this gives following error 
elasticsearch.exceptions.RequestError: TransportError(400, u'invalid_type_name_exception', u"Document mapping type name can't start with '_'")

**Comment by WisdomPill** [comment] 2018-01-24 08:56
Very strange behavior. I'm skeptical about the client initialization but it seems to work for me on my local machine. Can you please provide which version of elasticsearch, elasticsearch-dsl-py and python you're using? In the mean time I would suggest to you to use the configure connections to avoid repeating yourself every time you want to search something in elasticsearch.

```python
from elasticsearch_dsl import Search
from elasticsearch_dsl.connections import connections

conf = {
    'default': {
        'hosts': [
            {
                'host': '172.16.2.121',
                'port': 9200
            }
        ]
    }
}

connections.configure(**conf)

# elasticsearch dsl python falls back to the default connection by default if you don't specify it in the search object

s = Search(index="mqtt-index-2018.01.24").query("match", value=10)
response = s.delete()

print(response)
print(s.to_dict())
```

Hope it helps.

**Comment by HonzaKral** [comment] 2018-02-08 17:15
Since we cannot reproduce this, I will close this issue. Please feel free to reopen any time with more information.

Thank you @WisdomPill for the answer!

**Closed by HonzaKral** 2018-02-08 17:15 UTC

**Comment by m1schka** [comment] 2018-03-15 13:53
I would like to reopen this issue as I'm also affected. for me the problem is the suggest api in combination with ES 6.0 (no problems so far with 5.6). here is my stackstrace:
```
    suggestions = [hashtag._source for hashtag in hashtag_search.execute_suggest().filterSuggest[0].options]
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 654, in execute_suggest
    **self._params
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1227, in suggest
    '_suggest'), params=params, body=body)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'invalid_type_name_exception', "Document mapping type name can't start with '_', found: [_suggest]")
```

here is the related search:
```
class Hashtag(DocType):
    typeId = Text(fields={'keyword': Keyword()})
    slug = Text(fields={'keyword': Keyword()})
    name = Text(fields={'keyword': Keyword()}, analyzer=autocomplete_analyzer,
                search_analyzer='standard')
    nameSuggest = Completion()

    class Meta:
        index = 'filter_v1'


hashtag_search = Hashtag.search().suggest('filterSuggest', q,
                                                      completion={'field': 'nameSuggest',
                                                                  })
# assuming exactly one return value and structure based on
# https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters-completion.html#querying
suggestions = [hashtag._source for hashtag in hashtag_search.execute_suggest().filterSuggest[0].options]
```

I need to support two ES versions, 5.6 and 6 and I just saw there is a dedicated version for 6. is that maybe the reason? do you have any suggestions for me?

**Comment by HonzaKral** [comment] 2018-03-15 14:07
Yes, this is the reason. You can go around that by using `elasticsearch` and `elasticsearch5` which you can both install at the same time. Then you just need to configure the `connections` object to use proper version for different clusters:
```python
from elasticsearch_dsl import connections
from elasticsearch import Elasticsearch as Elasticsearch6
from elasticsearch5 import Elasticsearch as Elasticsearch5
connections.add_connection('default', Elasticsearch6(...))
connections.add_connection('older', Elasticsearch5(...))
```

The `dsl` library itself is mostly agnostic to versions but you need to pay attention to what features and options you specify for each version.

I hope this helps!

**Comment by HonzaKral** [comment] 2018-03-15 14:08
@m1schka also `execute_suggest` is not available in elasticsearch 6, you need to just use `execute`
