### ISSUE TITLE
TransportError 503,  No Shard Available Action Exception

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-dsl-py#231] opened 2015-08-04 09:47 UTC
Hi everyone,

I am having problems when I am looking for a register inside of an index and the message is the next:

When I do:

customer_history.get(id="oid:customer:0" ,index=index_gompute_history,ignore=404)

Where customer_history is definited as:

class customer_history(DocType)

The error is:

TransportError: TransportError(503, u'NoShardAvailableActionException[[new_gompute_history][2] null]; nested: IllegalIndexShardStateException[[new_gompute_history][2] CurrentState[POST_RECOVERY] operations only allowed when started/relocated]; ')

This comes when I am searching by an id inside of an index.

The health of my cluster is green:

GET _cat/health?v

epoch      timestamp cluster status node.total node.data shards pri relo init unassign 
1438678496 10:54:56  juan    green           5         4    212 106    0    0        0 

GET _cat/allocation?v

shards disk.used disk.avail disk.total disk.percent host    ip         node                   
    53     3.1gb     16.8gb       20gb           15 bc10-05 10.8.5.15  Anomaloco              
    53     6.4gb     80.8gb     87.3gb            7 bc10-03 10.8.5.13  Algrim the Strong      
     0        0b                                    l8a     10.8.0.231 logstash-l8a-5920-4018 
    53     6.4gb     80.8gb     87.3gb            7 bc10-03 10.8.5.13  Harry Leland           
    53     3.1gb     16.8gb       20gb           15 bc10-05 10.8.5.15  Hypnotia

Has somebody any idea about this?

Thanks in advance

**Comment by HonzaKral** [comment] 2015-08-13 14:06
Could you please run `GET _cal/shards?v` ?

It looks like some shards are not running, though allocated.

My guess would be that this is due to your disk space being low (85%) the disk allocator refuses to allocate more shards on your nodes (https://www.elastic.co/guide/en/elasticsearch/reference/1.6/index-modules-allocation.html#disk)

**Comment by HonzaKral** [comment] 2015-08-27 21:19
This looks to be problem with your elasticsearch instance. Since there is no more information and it is not reproducible, closing the issue.

**Closed by HonzaKral** 2015-08-27 21:19 UTC
