### ISSUE TITLE
search.source and search.filter order

### ISSUE THREAD

**Issue by jroxendal** [elastic/elasticsearch-dsl-py#388] opened 2016-04-08 11:13 UTC
I expect these to give the same result:
`search.source(exclude=["myfield"]).filter("firstname", field="john")`
and
`search.filter("firstname", field="john").source(exclude=["myfield"])`

in the latter case, `to_dict()` reveals `_source` to be missing from the request json.

**Comment by jroxendal** [comment] 2016-04-08 11:21
pinging feature author @andybarilla

**Comment by HonzaKral** [comment] 2016-04-08 11:25
Could you please share more of your code? From your snippets I cannot replicate it:
```
>>> from elasticsearch_dsl import Search
>>> search = Search()
>>> search.source(exclude=["myfield"]).filter("terms", field="john").to_dict()
{'_source': {'exclude': ['myfield']}, 'query': {'bool': {'filter': [{'terms': {'field': 'john'}}]}}}
>>> search.filter("terms", field="john").source(exclude=["myfield"]).to_dict()
{'_source': {'exclude': ['myfield']}, 'query': {'bool': {'filter': [{'terms': {'field': 'john'}}]}}}
```
Thanks

**Comment by HonzaKral** [comment] 2016-04-08 11:26
Note that your `filter` was wrong, there is no filter or query called `"firstname"` so I changed it to `"terms"` for my reproduction. If you were ignoring the exception that it threw it would account for the behavior you are seeing.

**Comment by jroxendal** [comment] 2016-04-08 12:31
Yeah, sorry about the broken example, my actual code is more like this (in a flask handler):

    search = Search(using=es, index="myindex") \
        .filter("exists", field="epub")
    if request.args.get("include"):
        search.source(include=request.args.get("include").split(","))

    return search.execute() 


from what I can see the code above drops my context after the chaining syntax block, and the `search` variable is reset to `{'query': {'match_all': {}}}` instead of the filter i added above. that's not what I would have expected from having used similar chaining APIs (eg jQuery). is this behavior intended?

**Comment by jroxendal** [comment] 2016-04-08 12:39
minimal example explaining my confusion:

    s = Search(using=es, index="litteraturbanken")
    s.filter("exists", field="epub") # prints: {'query': {'match_all': {}}}
    print(s.to_dict())

    s2 = Search(using=es, index="litteraturbanken").filter("exists", field="epub")
    print(s2.to_dict()) # prints: {'query': {'bool': {'filter': [{'exists': {'field': 'epub'}}]}}}

**Comment by njoannin** [comment] 2016-04-08 12:55
@jroxendal 

Your error is that you are not assigning ```s.filter("exists", field="epub")``` to "s".

You need to do:

```
s = Search(using=es, index="litteraturbanken")
s = s.filter("exists", field="epub")
```

**Comment by HonzaKral** [comment] 2016-04-08 12:55
I see, the issue is that any of the `Search` methods (like `filter` or `source`) actually return a modified version of the object so you need to keep assigning it back to `s`.

**Comment by HonzaKral** [comment] 2016-04-08 12:56
Ah, thanks @njoannin! You beat me to it :)

I am closing this issue, please feel free to reopen if the solution doesn't work for you. Thanks!

**Comment by jroxendal** [comment] 2016-04-08 12:57
sorry, my bad, thanks for the nice lib!

**Closed by HonzaKral** 2016-04-08 12:56 UTC
