### ISSUE TITLE
Validation Error -- use `if_seq_no`

### ISSUE THREAD

**Issue by akajb84** [elastic/elasticsearch-dsl-py#1357] opened 2020-05-05 17:41 UTC
I have a case where we are slowly shifting from ES5 to ES7. Unfortunately, because of the current system, we need to support ES5 during this time, which means we can't use the latest version of elasticsearch-dsl, and instead are stuck using es-dsl 6.4 until we can finally remove our ES5 code (which is not using es-dsl). :( 

I'm running into a problem when trying to save changes to an existing document. Specifically the following validation error to do with using the internal versioning number.

`RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: internal versioning can not be used for optimistic concurrency control. Please use `if_seq_no` and `if_primary_term` instead;')`

If I switch over to es-dsl >7, the code works fine, but not with es-dsl 6.4. Is there a way to work around this for now? Can I update information in the meta fields or something?

**Comment by ajlouie** [comment] 2023-09-20 21:36
The problem is that the version passed to `elasticsearch` defaults to `1` if you don't specify it in the `elasticsearch_dsl` method call.

Passing `version=None` as a parameter to the `update` or `delete` method seems to do the trick for me with these versions:
```
elasticsearch==6.8.2
elasticsearch-dsl==6.4.0
```

**Comment by pquentin** [comment] 2023-09-21 05:55
Thanks @ajlouie for the help. Closing this issue then.

**Closed by pquentin** 2023-09-21 05:55 UTC
