### ISSUE TITLE
Elasticsearch attribute name different from Python name

### ISSUE THREAD

**Issue by lschmelzeisen** [elastic/elasticsearch-dsl-py#1345] opened 2020-04-19 08:49 UTC
Hi, I currently have a document definition similar to the following:

```python
class BlogPost(Document):
    title = Text()
    content = Text()
    type = Keyword()
```

However, my code style dictates that I avoid shadowing Python-interals, such as [type()](https://docs.python.org/3/library/functions.html#type) here.

Therefore, I'd like to change the name of the class attribute *without changing the name in the Elasticsearch mapping*. I'm thinking of syntax similar to the following:

```python
class BlogPost(Document):
    title = Text()
    content = Text()
    type_ = Keyword(name="type")
```

Is something like this supported?

**Comment by lschmelzeisen** [comment] 2020-05-06 12:48
I just noticed that there is an even better reason for needing this. I currently have an ElasticSearch index with a mapping that I do not want to change (to expensive to reindex). Here `from` is used as a field name. Is there any way to assign a mapping to this field with elasticsearch-dsl?

```python
class BlogPost(Document):
    from = Keyword()
```

The conventional way of having it as a class attribute fails because `from` is a Python keyword and not allowed in this place.

**Comment by craynic** [comment] 2020-07-07 13:26
It seems that you could use an attribute `mapping` in `class Meta` to define extra fields.
[link](https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#class-meta-options)

**Comment by lschmelzeisen** [comment] 2020-07-10 13:55
I'm not sure whether this does what I need it to do. Would you mind to provide some short example code?

**Comment by miguelgrinberg** [comment] 2024-03-25 17:17
Also mentioned in #1659

**Comment by miguelgrinberg** [comment] 2024-04-26 15:04
Closing this one, since it is a duplicate of #1659

**Closed by miguelgrinberg** 2024-04-26 15:04 UTC
Labels: Category: Enhancement
