### ISSUE TITLE
Persistence get request

### ISSUE THREAD

**Issue by jredd** [elastic/elasticsearch-dsl-py#186] opened 2015-06-25 15:34 UTC
Right now when request a doc by id you get back that doc but if I doesn't exist the script tosses Transport error NotFoundError. Why not just have it return None?

**Comment by HonzaKral** [comment] 2015-06-25 16:18
Because the reasonable expectation here is to be able to get the document. The document not being there is an exceptional state and therefore is marked with an exception. If you wish to return `None`, pass in `ignore=404`. It was documented in https://github.com/elastic/elasticsearch-dsl-py/commit/ecbd230db425b2f41b176b2f05d0d5e0c516239f.

Closing this issue as duplicate of #88

**Closed by HonzaKral** 2015-06-25 16:18 UTC

**Comment by jredd** [comment] 2015-06-25 16:27
Unfortunetly when I use the above method and tell the get request to ignore 404 it does not return None but returns an empty dict {}... Thats still usable just figured you would want to know that whats documented isn't exactly whats happening.

**Comment by HonzaKral** [comment] 2015-06-25 16:52
In what version of the library? It works on master, which is where the documentation is: https://github.com/elastic/elasticsearch-dsl-py/blob/master/test_elasticsearch_dsl/test_integration/test_document.py#L43-L48

**Comment by jredd** [comment] 2015-06-26 18:51
I'm on version 0.0.4 installed via pycharm.
