### ISSUE TITLE
Expand__to_dot variable cannot be used to control the behavior

### ISSUE THREAD

**Issue by samv-yazzoom** [elastic/elasticsearch-dsl-py#1633] opened 2022-11-09 12:07 UTC
Hello,

This pull request: https://github.com/elastic/elasticsearch-dsl-py/pull/809 moved the default for _expand__to_dot to a variable.
At load time, the default for _expand__to_dot will already be set to True. Overwriting EXPAND__TO_DOT after the import has not impact.

The variable would be usable if the default is resolved in the function definition.

**Comment by miguelgrinberg** [comment] 2024-03-25 17:01
Duplicate of #1586

**Closed** 2024-04-11 14:33 UTC
Labels: bug
