### ISSUE TITLE
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

### ISSUE THREAD

**Issue by stefansaye** [elastic/elasticsearch-dsl-py#472] opened 2016-10-12 15:36 UTC
hi all,
I am not able to understand why this error happens:

```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, {u'caused_by': 
{u'reason': u'max_bytes_length_exceeded_exception: bytes can be at most 32766 in length; got 37359',     u'type': u'max_bytes_length_exceeded_exception'},
```

Thanks in advance

**Comment by HonzaKral** [comment] 2016-10-12 15:40
Hi @stefansaye ,

you seem to have a value in your `traceback` field that is too long - over `32766` - and are trying to index it as a single term (perhaps using `index="not_analyzed"`?).

Assuming the field contains actual traceback from some exception it makes little sense to actually index it as not analyzed. If you indeed have to then it would be best to limit the size of the token by using `ignore_above` - https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html

Hope this helps!

**Comment by stefansaye** [comment] 2016-10-12 15:50
Hi @HonzaKral ,
  Is it possible to know which value in traceback field ?

**Comment by HonzaKral** [comment] 2016-10-12 15:56
Well, the one that raised this error when you tried to index it, what was the code that produced the error? The error message also specifies the prefix in bytes.

**Comment by HonzaKral** [comment] 2016-11-30 12:53
Closing this issue since there is no additional information. Please feel free to reopen with more details, Thank You!

**Closed by HonzaKral** 2016-11-30 12:53 UTC

**Comment by ShwethaThakur** [comment] 2018-07-21 07:05
doc_type, '_mtermvectors'), params=params, body=body)
  File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'too_long_frame_exception', u'An HTTP line is larger than 4096 bytes.')

Hey there! i am trying to use multitemvectors in elasticsearch to get most frequent unigrams, bigrams and trigrams across an entire index. The number of documents is approx. 50000. When i give 300 IDs, it works fine. But When i give all IDs of 50000 documents, it raises this error. Doesn't multitermvectors work with large no. of documents? or is there a way to figure out this error?

**Comment by HonzaKral** [comment] 2018-07-21 15:15
The problem is that the HTTP line is larger then the allowed limit. So you need to make sure you either pass the list of IDs in the body, if possible, or never exceed that limit.

Also please direct your issues to `elasticsearch-py` since that is the API you are using, this repository is for the `elasticsearch_dsl` library that doesn't support the `termvercors` API

**Comment by ShwethaThakur** [comment] 2018-07-22 03:12
So there isn't any way to pass all IDs as parameter to mtermvectors
function?I have tried to get all IDs as query and stored it in a variable.
Passed that variable as parameter. Still get the same error!

**Comment by HonzaKral** [comment] 2018-07-22 03:57
It depends on how you are passing in the data. But that is not an issue with elasticsearch-dsl so I will ask you to please open this issue at https://github.com/elastic/elasticsearch-py

Thank you!
