### ISSUE TITLE
Could not parse date from the value

### ISSUE THREAD

**Issue by alexm92** [elastic/elasticsearch-dsl-py#502] opened 2016-11-07 11:21 UTC
I am getting this error, some times, while I scan documents for an export:

```
elasticsearch_dsl.exceptions:ValidationException: 
Could not parse date from the value (u'2016-11-03T21:46:09.278914+00:00')
```

Traceback:
```
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/search.py", line 666, in scan
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 216, in from_es
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 108, in __init__
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/utils.py", line 339, in __init__
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/field.py", line 76, in deserialize
File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/field.py", line 224, in _deserialize
```

Using:
```
Elasticsearch 2.4.0
elasticsearch==2.4.0
elasticsearch-dsl==2.1.0
```

Any ideas why and how to fix it?

Parsing the date works, as can be seen in the example below taken from repo  https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/field.py#L222:

```
from dateutil import parser

x = '2016-11-03T21:46:09.278914+00:00'
print parser.parse(x) # will output 2016-11-03 21:46:09.278914+00:00
```

**Comment by HonzaKral** [comment] 2016-11-30 13:01
Thanks for the great report and apologies for taking so long to respond.

This is very weird behavior and shouldn't be happening. Could you please try and inspect the exception you are getting as there should be the original exception we are wrapping attached to it. That should give us more information.

Thank you!

**Comment by HonzaKral** [comment] 2016-12-30 16:00
I cannot reproduce this error so I am closing this issue. Please feel free to reopen with additional information. Thank you

**Closed by HonzaKral** 2016-12-30 16:00 UTC
